"""Bloodbank table.

Revision ID: 3e2d33e8fae9
Revises: 107dd64d47f1
Create Date: 2024-01-24 17:02:41.944148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2d33e8fae9'
down_revision = '107dd64d47f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloodbank',
    sa.Column('b_group', sa.String(length=100), nullable=False),
    sa.Column('total_packets', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('b_group')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bloodbank')
    # ### end Alembic commands ###
