"""finished

Revision ID: 41676ba1e92c
Revises: 
Create Date: 2024-01-25 09:27:33.986350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41676ba1e92c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloodbank',
    sa.Column('b_group', sa.String(length=100), nullable=False),
    sa.Column('total_packets', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('b_group')
    )
    op.create_table('donor',
    sa.Column('D_id', sa.Integer(), nullable=False),
    sa.Column('Dname', sa.String(length=100), nullable=True),
    sa.Column('Demail', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('donor_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('D_id')
    )
    op.create_table('reception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood',
    sa.Column('b_code', sa.Integer(), nullable=False),
    sa.Column('D_id', sa.Integer(), nullable=True),
    sa.Column('packets', sa.Integer(), nullable=True),
    sa.Column('B_group', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['D_id'], ['donor.D_id'], ),
    sa.PrimaryKeyConstraint('b_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blood')
    op.drop_table('reception')
    op.drop_table('donor')
    op.drop_table('bloodbank')
    # ### end Alembic commands ###
