"""Initial migration.

Revision ID: 63782e03f2f6
Revises: 
Create Date: 2024-01-24 16:38:57.455946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63782e03f2f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetion')
    # ### end Alembic commands ###
