"""Donor table.

Revision ID: b488aff91352
Revises: 5dab76e9b81a
Create Date: 2024-01-24 16:55:53.336318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b488aff91352'
down_revision = '5dab76e9b81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doners',
    sa.Column('D_id', sa.Integer(), nullable=False),
    sa.Column('Dname', sa.String(length=100), nullable=True),
    sa.Column('Demail', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('donor_Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('D_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doners')
    # ### end Alembic commands ###
